import {
    Address,
    CHAIN_TO_WRAPPER as FUSION_CHAIN_TO_WRAPPER
} from '@1inch/fusion-sdk'
import {EvmChain, NetworkEnum} from './chains.js'
import {EvmAddress} from './domains/addresses/index.js'

export const CHAIN_TO_WRAPPER: Record<EvmChain, Address> = {
    ...FUSION_CHAIN_TO_WRAPPER,
    [NetworkEnum.ROBINHOOD]: new Address(
        '0x0bd7d308f8e1639fab988df18a8011f41eacad73'
    )
}

const TrueERC20 = EvmAddress.fromString(
    '0xda0000d4000015a526378bb6fafc650cea5966f8'
)
const ZKTrueERC20 = EvmAddress.fromString(
    '0xd66097c27eb8dee404bac235737932260edc6f3b'
)
// Robinhood chain uses its own CREATE3 deployer, so addresses differ from other chains
const RobinhoodTrueERC20 = EvmAddress.fromString(
    '0x40c0b7e8018cca1eb8d913b75b1b20cfd89b8d5b'
)

export const TRUE_ERC20 = {
    [NetworkEnum.ETHEREUM]: TrueERC20,
    [NetworkEnum.POLYGON]: TrueERC20,
    [NetworkEnum.OPTIMISM]: TrueERC20,
    [NetworkEnum.BINANCE]: TrueERC20,
    [NetworkEnum.AVALANCHE]: TrueERC20,
    [NetworkEnum.COINBASE]: TrueERC20,
    [NetworkEnum.FANTOM]: TrueERC20,
    [NetworkEnum.GNOSIS]: TrueERC20,
    [NetworkEnum.ARBITRUM]: TrueERC20,
    [NetworkEnum.ZKSYNC]: ZKTrueERC20,
    [NetworkEnum.LINEA]: TrueERC20,
    [NetworkEnum.SONIC]: TrueERC20,
    [NetworkEnum.UNICHAIN]: TrueERC20,
    [NetworkEnum.ROBINHOOD]: RobinhoodTrueERC20
}

const ESCROW_FACTORY_ADDRESS = EvmAddress.fromString(
    '0xa7bcb4eac8964306f9e3764f67db6a7af6ddf99a'
)
const ESCROW_ZK_FACTORY_ADDRESS = EvmAddress.fromString(
    '0x584aeab186d81dbb52a8a14820c573480c3d4773'
)
const ESCROW_SRC_IMPLEMENTATION_ADDRESS = EvmAddress.fromString(
    '0xcd70bf33cfe59759851db21c83ea47b6b83bef6a'
)
const ESCROW_ZK_SRC_IMPLEMENTATION_ADDRESS = EvmAddress.fromString(
    '0xddc60c7babfc55d8030f51910b157e179f7a41fc'
)
const ESCROW_DST_IMPLEMENTATION_ADDRESS = EvmAddress.fromString(
    '0x9c3e06659f1c34f930ce97fcbce6e04ae88e535b'
)
const ESCROW_ZK_DST_IMPLEMENTATION_ADDRESS = EvmAddress.fromString(
    '0xdc4ccc2fc2475d0ed3fddd563c44f2bf6a3900c9'
)
// Robinhood chain uses its own CREATE3 deployer, so addresses differ from other chains
const ESCROW_RH_FACTORY_ADDRESS = EvmAddress.fromString(
    '0xa02b9cc95094bb27d1d041b9fbf09f65a366f7b3'
)
const ESCROW_RH_SRC_IMPLEMENTATION_ADDRESS = EvmAddress.fromString(
    '0xb077a4326f1e875c21d74028a1499eafcee43bf3'
)
const ESCROW_RH_DST_IMPLEMENTATION_ADDRESS = EvmAddress.fromString(
    '0x104f09ea1f9c09662635ad581d0bef8b15d16f4f'
)

export const ESCROW_SRC_IMPLEMENTATION = {
    [NetworkEnum.ETHEREUM]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.POLYGON]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.OPTIMISM]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.BINANCE]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.AVALANCHE]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.COINBASE]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.FANTOM]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.GNOSIS]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.ARBITRUM]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.ZKSYNC]: ESCROW_ZK_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.LINEA]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.SONIC]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.UNICHAIN]: ESCROW_SRC_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.ROBINHOOD]: ESCROW_RH_SRC_IMPLEMENTATION_ADDRESS
}

export const ESCROW_DST_IMPLEMENTATION = {
    [NetworkEnum.ETHEREUM]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.POLYGON]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.OPTIMISM]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.BINANCE]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.AVALANCHE]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.COINBASE]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.FANTOM]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.GNOSIS]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.ARBITRUM]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.ZKSYNC]: ESCROW_ZK_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.LINEA]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.SONIC]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.UNICHAIN]: ESCROW_DST_IMPLEMENTATION_ADDRESS,
    [NetworkEnum.ROBINHOOD]: ESCROW_RH_DST_IMPLEMENTATION_ADDRESS
}

export const ESCROW_FACTORY = {
    [NetworkEnum.ETHEREUM]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.POLYGON]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.OPTIMISM]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.BINANCE]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.AVALANCHE]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.COINBASE]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.FANTOM]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.GNOSIS]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.ARBITRUM]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.ZKSYNC]: ESCROW_ZK_FACTORY_ADDRESS,
    [NetworkEnum.LINEA]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.SONIC]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.UNICHAIN]: ESCROW_FACTORY_ADDRESS,
    [NetworkEnum.ROBINHOOD]: ESCROW_RH_FACTORY_ADDRESS
}
